config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "restaurants#index"

  namespace :admin do
    get "dashboard/index"
  end

  get "up" => "rails/health#show", as: :rails_health_check

  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: { safari: 16, firefox: 110, ie: 9 }

  def check_admin
    unless current_user.admin?
      redirect_to root_path, alert: "You are not authorized to access this page."
    end
  end

  def is_admin
    current_user && current_user.admin?
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  before_action :authenticate_user!, only: %i[edit update destroy]
  before_action :check_admin, only: %i[edit update destroy]

  def index
    @restaurants = Restaurant.order(created_at: :desc)
    @is_admin = is_admin
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    update_params = restaurant_params

    if params[:restaurant][:photos] == [ "" ]
      update_params = params.require(:restaurant).except(:photos).permit(:name, :address, :review)
    end

    if @restaurant.update(update_params)
      redirect_to @restaurant, notice: "Restaurant was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: "Restaurant was successfully destroyed."
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :review, photos: [])
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    markdown = Redcarpet::Markdown.new(renderer, autolink: true, tables: true, fenced_code_blocks: true)
    markdown.render(text).html_safe
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/dashboard/index.html.erb
<h2>Admin Dashboard</h2>

<%= link_to 'home', restaurants_path %>
<%= button_to 'Logout', destroy_user_session_path, method: :delete %>
<%= button_to 'New restaurant', new_restaurant_path, method: :get %>

<table class="restaurant-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each_with_index do |restaurant, index| %>
      <tr class="<%= 'odd-row' if index.odd? %>">
        <td><%= restaurant.name %></td>
        <td>
          <div class="restaurant-action-contailer">
            <%= button_to 'Edit', edit_restaurant_path(restaurant), method: :get, class: "edit-button" %>
            |
            <%= form_with model: restaurant, method: :delete, local: true do |form| %>
              <%= form.submit 'Delete', class: 'delete-button', id: "delete-btn-#{restaurant.id}" %>
            <% end %>
          </div>
          

          <script>
            document.getElementById('delete-btn-<%= restaurant.id %>').addEventListener('click', function(event) {
              if (!confirm('Are you sure you want to delete this <%= restaurant.name %>?')) {
                event.preventDefault();
              }
            });
          </script>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hart and Henry eat food" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h2>Edit Restaurant</h2>

<%= form_with model: @restaurant, local: true, enctype: "multipart/form-data" do |form| %>
  <% if @restaurant.errors.any? %>
    <div>
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :review %>
    <%= form.text_area :review, class: "textarea-large" %>
  </div>

  <div class="markdown-options">
    <pre>
      **Bold Text**: Makes text bold.
      *Italic Text*: Makes text italic.
      `Code`: Renders text as code block.
      [Link](http://example.com): Creates a hyperlink.
      - List item: Creates a list.
    </pre>
  </div>

  <div>
    <%= form.label :photos %>
    <%= form.file_field :photos, multiple: true, direct_upload: true, class: 'photo-upload', onchange: 'previewPhotos(event)' %>
    
    <div id="photo-preview" class="edit-restaurant-images">
      <% if @restaurant.photos.attached? %>
        <% @restaurant.photos.each do |photo| %>
          <div class="existing-photo">
            <%= image_tag(photo, class: "restaurant-photo") %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div>
    <%= form.submit "Update Restaurant" %>
  </div>
<% end %>

<%= link_to 'Back', admin_dashboard_index_path %>



<script>
  function previewPhotos(event) {
    const photoPreview = document.getElementById('photo-preview');
    const files = event.target.files;

    if (files.length > 0) {
      const currentPreviewImages = photoPreview.querySelectorAll('.restaurant-photo');
      currentPreviewImages.forEach(img => img.remove());
    }

    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      const reader = new FileReader();

      reader.onload = function(e) {
        const img = document.createElement('div');
        img.classList.add('preview-photo');
        img.innerHTML = `<img src="${e.target.result}" class="restaurant-photo">`;
        photoPreview.appendChild(img);
      }

      reader.readAsDataURL(file);
    }
  }
</script>

app/views/restaurants/index.html.erb
<div class="restaurants-main-container">
  <%= image_tag "little_food_drawings/pasta.png", alt: "we like to eat!", class: "little-food-drawing" %>
  <div class="restaurants-container">
    <% if @is_admin %>
      <%= link_to "Edit", admin_dashboard_index_path %>
    <% end %>
    <% @restaurants.each do |restaurant| %>
      <div class="restaurant-card">
        <div>
          <%= link_to restaurant.name, restaurant_path(restaurant), class: "restaurant-name" %>
          <p class="restaurant-address"><%= restaurant.address %></p>
          <p class="restaurant-review"> <%= markdown(restaurant.review) %></p>

          <% if restaurant.photos.any? %>
            <div class="restaurant-photos">
              <% restaurant.photos.first(3).each do |photo| %>
                <%= link_to restaurant_path(restaurant) do %>
                  <%= image_tag(photo, class: "restaurant-photo") %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>

<%= form_with model: @restaurant, local: true, enctype: "multipart/form-data" do |form| %>
  <% if @restaurant.errors.any? %>
    <div>
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div>
    <%= form.label :photos %>
    <%= form.file_field :photos, multiple: true %> <!-- Multiple files upload -->
  </div>

  <div>
    <%= form.submit "Create Restaurant" %>
  </div>
<% end %>

<%= link_to 'Back', admin_dashboard_index_path %>

app/views/restaurants/show.html.erb
<div class="restaurants-container">
  <%= link_to 'back', restaurants_path %>
  <p class="restaurant-name-unclickable"><%= @restaurant.name %></p>
  <p class="restaurant-address"><%= @restaurant.address %></p>
  <p class="restaurant-review"> <%= markdown(@restaurant.review) %></p>

  <% if @restaurant.photos.any? %>
    <div class="restaurant-photos">
      <% @restaurant.photos.each do |photo| %>
        <%= image_tag(photo, class: "restaurant-photo") %>
      <% end %>
    </div>
  <% end %>
</div>